/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projets: Projet;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projets: ProjetsSelect<false> | ProjetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    footer: Footer;
    nav: Nav;
    links: Link;
    aside: Aside;
    seo: Seo;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
    nav: NavSelect<false> | NavSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    aside: AsideSelect<false> | AsideSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL de la page (ex: accueil)
   */
  slug: string;
  pageType: 'home' | 'standard' | 'contact' | 'estimate';
  /**
   * Titre affiché dans les résultats de recherche (50-60 caractères recommandés)
   */
  metaTitle?: string | null;
  /**
   * Description affichée dans les résultats de recherche (150-160 caractères recommandés)
   */
  metaDescription?: string | null;
  /**
   * Mots-clés séparés par des virgules (ex: web, design, développement)
   */
  keywords?: string | null;
  /**
   * URL canonique de la page (laissé vide pour utiliser l'URL automatique)
   */
  canonicalUrl?: string | null;
  header?: {
    tag?: string | null;
    heading?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  contactPage?: {
    title?: string | null;
    intro?: string | null;
    infos?: {
      who?: {
        title?: string | null;
        options?:
          | {
              label?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
      };
      what?: {
        title?: string | null;
        options?:
          | {
              label?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
      };
    };
  };
  estimatePage?: {
    title?: string | null;
    intro?: string | null;
    infos?: {
      who?: {
        title?: string | null;
        options?:
          | {
              label?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
      };
      what?: {
        title?: string | null;
        options?:
          | {
              label?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
      };
    };
  };
  projects?: {
    enabled?: boolean | null;
    title?: string | null;
    button?: {
      href?: string | null;
      text?: string | null;
      icon?: ('arrow' | 'calendar' | 'estimate' | 'link') | null;
      border?: boolean | null;
    };
    subtitle?: string | null;
    description?: string | null;
    projectsList?:
      | {
          project?: (number | null) | Projet;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageCredit?: string | null;
    ctaButtons?: {
      variant?: ('primary' | 'secondary') | null;
      href?: string | null;
      title?: string | null;
      icon?: ('arrow' | 'calendar' | 'estimate' | 'link') | null;
      border?: boolean | null;
    };
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  services?: {
    enabled?: boolean | null;
    tag?: string | null;
    title?: string | null;
    description?: string | null;
    servicesList?:
      | {
          icon?: ('custom' | 'cart' | 'rocket' | 'code' | 'shipping') | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaLink?: string | null;
    ctaText?: string | null;
  };
  expertises?: {
    enabled?: boolean | null;
    tag?: string | null;
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    button?: {
      href?: string | null;
      text?: string | null;
      icon?: ('arrow' | 'calendar' | 'estimate' | 'link') | null;
      border?: boolean | null;
    };
    expertisesList?:
      | {
          label?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  offers?: {
    enabled?: boolean | null;
    tag?: string | null;
    title?: string | null;
    offersList?:
      | {
          icon?: ('rocket' | 'bag' | 'cart') | null;
          title?: string | null;
          description?: string | null;
          price?: string | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projets".
 */
export interface Projet {
  id: number;
  title: string;
  /**
   * URL du projet (ex: beaurecit)
   */
  slug: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  published?: boolean | null;
  sections?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  websiteUrl?: string | null;
  websiteButtonText?: string | null;
  /**
   * Titre affiché dans les résultats de recherche (50-60 caractères recommandés)
   */
  metaTitle?: string | null;
  /**
   * Description affichée dans les résultats de recherche (150-160 caractères recommandés)
   */
  metaDescription?: string | null;
  /**
   * Mots-clés séparés par des virgules (ex: web, design, développement)
   */
  keywords?: string | null;
  /**
   * URL canonique du projet (laissé vide pour utiliser l'URL automatique)
   */
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projets';
        value: number | Projet;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  canonicalUrl?: T;
  header?:
    | T
    | {
        tag?: T;
        heading?: T;
        description?: T;
      };
  contactPage?:
    | T
    | {
        title?: T;
        intro?: T;
        infos?:
          | T
          | {
              who?:
                | T
                | {
                    title?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                  };
              what?:
                | T
                | {
                    title?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                  };
            };
      };
  estimatePage?:
    | T
    | {
        title?: T;
        intro?: T;
        infos?:
          | T
          | {
              who?:
                | T
                | {
                    title?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                  };
              what?:
                | T
                | {
                    title?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                  };
            };
      };
  projects?:
    | T
    | {
        enabled?: T;
        title?: T;
        button?:
          | T
          | {
              href?: T;
              text?: T;
              icon?: T;
              border?: T;
            };
        subtitle?: T;
        description?: T;
        projectsList?:
          | T
          | {
              project?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        image?: T;
        imageCredit?: T;
        ctaButtons?:
          | T
          | {
              variant?: T;
              href?: T;
              title?: T;
              icon?: T;
              border?: T;
            };
      };
  content?: T;
  services?:
    | T
    | {
        enabled?: T;
        tag?: T;
        title?: T;
        description?: T;
        servicesList?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        ctaLink?: T;
        ctaText?: T;
      };
  expertises?:
    | T
    | {
        enabled?: T;
        tag?: T;
        title?: T;
        content?: T;
        button?:
          | T
          | {
              href?: T;
              text?: T;
              icon?: T;
              border?: T;
            };
        expertisesList?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  offers?:
    | T
    | {
        enabled?: T;
        tag?: T;
        title?: T;
        offersList?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              price?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projets_select".
 */
export interface ProjetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  image?: T;
  published?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  websiteUrl?: T;
  websiteButtonText?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Adresse email affichée dans le footer
   */
  email: string;
  navLinks?:
    | {
        label: string;
        /**
         * URL ou ancre (ex: #projets ou /page)
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        variant?: ('primary' | 'secondary') | null;
        href: string;
        title: string;
        icon?: ('calendar' | 'estimate' | 'arrow' | 'link') | null;
        border?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL du profil LinkedIn
   */
  linkedinUrl?: string | null;
  legalLinks?:
    | {
        /**
         * Sélectionner une page existante
         */
        page: number | Page;
        id?: string | null;
      }[]
    | null;
  /**
   * Texte de copyright affiché dans le footer
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  name?: string | null;
  job?: string | null;
  href?: string | null;
  navLinks?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        variant?: ('primary' | 'secondary') | null;
        href?: string | null;
        title?: string | null;
        icon?: ('arrow' | 'calendar' | 'estimate' | 'link') | null;
        border?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  ctaButtons?:
    | {
        variant?: ('primary' | 'secondary') | null;
        href?: string | null;
        title?: string | null;
        icon?: ('arrow' | 'calendar' | 'estimate' | 'link') | null;
        border?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL du profil LinkedIn
   */
  linkedinUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aside".
 */
export interface Aside {
  id: number;
  title?: string | null;
  href?: string | null;
  icon?: ('arrow' | 'calendar' | 'estimate' | 'link') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Nom du site utilisé dans les métadonnées Open Graph
   */
  siteName: string;
  /**
   * URL complète du site (ex: https://www.exemple.com)
   */
  siteUrl: string;
  /**
   * Description utilisée par défaut si aucune description n'est définie pour une page
   */
  defaultDescription?: string | null;
  /**
   * URL de la page LinkedIn (optionnel)
   */
  linkedinPage?: string | null;
  /**
   * Image utilisée par défaut pour le partage sur les réseaux sociaux (1200x630px recommandé)
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Favicon du site (format ICO ou PNG, 32x32px recommandé)
   */
  favicon?: (number | null) | Media;
  /**
   * Nom de l'auteur par défaut du site
   */
  authorName?: string | null;
  /**
   * Email de l'auteur (optionnel)
   */
  authorEmail?: string | null;
  /**
   * Site web ou profil de l'auteur (optionnel)
   */
  authorUrl?: string | null;
  /**
   * Nom de l'organisation pour le Structured Data
   */
  organizationName?: string | null;
  /**
   * Logo de l'organisation pour le Structured Data
   */
  organizationLogo?: (number | null) | Media;
  /**
   * URL du site web de l'organisation
   */
  organizationUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  email?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        variant?: T;
        href?: T;
        title?: T;
        icon?: T;
        border?: T;
        id?: T;
      };
  linkedinUrl?: T;
  legalLinks?:
    | T
    | {
        page?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  name?: T;
  job?: T;
  href?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        variant?: T;
        href?: T;
        title?: T;
        icon?: T;
        border?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  ctaButtons?:
    | T
    | {
        variant?: T;
        href?: T;
        title?: T;
        icon?: T;
        border?: T;
        id?: T;
      };
  linkedinUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aside_select".
 */
export interface AsideSelect<T extends boolean = true> {
  title?: T;
  href?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  defaultDescription?: T;
  linkedinPage?: T;
  defaultOgImage?: T;
  favicon?: T;
  authorName?: T;
  authorEmail?: T;
  authorUrl?: T;
  organizationName?: T;
  organizationLogo?: T;
  organizationUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}